# 该文件是 `aria2` 的下载配置文件,它默认读取的
# 路径是 `~/.aria2/aria2.conf`

# 设置下载的目录
dir=<path> # eg ~/Downloads/

# 启用断点续传
continue=true

# 同时下载的任务数量
max-concurrent-downloads=2

# 每一个任务的连接数
split=4
max-connection-per-server=4

#最小文件分片大小
min-split-size=1M

# 启用 BT 下载
enable-dht=true
enable-peer-exchange=true

# BT 端口,需要放开网络防火墙,下面两个属于不同协议可以使用相同端口
listen-port=<port>  # 监听的 udp 端口
dht-listen-port=<port> # 监听的 tcp 端口
#
# input_file 用以指定多个下载链接,会进行多任务下载
# input-file=<path> # eg ~/download.txt

# # 保存 session 下载状态,以便下次下载时自动恢复终止前状态
save-session=<path> # eg ~/.aria2/aria2.session
save-session-interval=30
#
# # 禁止自动重命名
auto-file-renaming=false
#
# # 下载时显示进度条
console-log-level=notice
summary-interval=60
#
# # 设置 user-agent（有些网站需要）
user-agent=Mozilla/5.0
#
# # BT 上传限制（防止上传太多）
seed-ratio=0.01
seed-time=1

# 用以解决下载慢的问题,可以从 https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt 进行获取,使用逗号拼接.
bt-tracker=udp://tracker.opentrackr.org:1337/announce,udp://open.demonii.com:1337/announce,udp://open.tracker.cl:1337/announce,udp://open.stealth.si:80/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker-udp.gbitt.info:80/announce,udp://explodie.org:6969/announce,udp://tracker.qu.ax:6969/announce,udp://opentracker.io:6969/announce,udp://tracker.dump.cl:6969/announce,udp://public.tracker.vraphim.com:6969/announce,udp://ns-1.x-fins.com:6969/announce,udp://exodus.desync.com:6969/announce,https://tracker.tamersunion.org:443/announce,http://www.torrentsnipe.info:2701/announce,http://www.genesis-sp.org:2710/announce,http://tracker810.xyz:11450/announce,http://tracker.xiaoduola.xyz:6969/announce,http://tracker.vanitycore.co:6969/announce,http://tracker.sbsub.com:2710/announce
# 目前最新的链接
# bt-tracker=udp://tracker.opentrackr.org:1337/announce,udp://open.demonii.com:1337/announce,udp://open.stealth.si:80/announce,udp://tracker.torrent.eu.org:451/announce,udp://exodus.desync.com:6969/announce,udp://tracker.skyts.net:6969/announce,udp://explodie.org:6969/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.qu.ax:6969/announce,udp://tracker.ololosh.space:6969/announce,udp://tracker.dump.cl:6969/announce,udp://retracker01-msk-virt.corbina.net:80/announce,udp://p4p.arenabg.com:1337/announce,udp://open.free-tracker.ga:6969/announce,udp://leet-tracker.moe:1337/announce,udp://isk.richardsw.club:6969/announce,udp://discord.heihachi.pw:6969/announce,udp://bt.ktrackers.com:6666/announce,http://www.torrentsnipe.info:2701/announce,http://www.genesis-sp.org:2710/announce
