# 该配置文件用以在 Linux 下启动 MangoHud 监控,它默认放在 ~/.config/MangoHub 目录下.
# 其它配置参看官方文档 `https://github.com/flightlessmango/MangoHud`

#legacy_layout=1
# 设置为单列展示
horizontal=0

# 样式
font_size=22
background_alpha=0.4
round_corners=5
text_color=FFFFFF
background_color=000000
#position=bottom-left
position=top-left
# 设置宽度
width=600
#height

# 设置横坐标偏移
# position必须要设置为top-left或者bottom-left
offset_x=1700
# 设置纵坐标偏移
offset_y=0

# 显示内容
time
# 移除时间前缀
#time_no_label
#fps=1
ram
# 关闭 frame 实时图表的展示
frame_timing=0
cpu_temp
cpu_text=i7-8700
gpu_temp
gpu_text=GTX-1070Ti
io_read
io_write
#display_server
