[sync.rsync]
# 设置 rsync 的文件路径,它的环境必须要与 python 的环境相同.
rsync_path = '/mnt/d/carl/soft/wsl/rsync/bin/rsync'

# 是否设置为安静模式,为 true 将不输出非错误日志
with_quiet = false

[[sync.path_list]]
# 监控的源目录
src_path = '<src_path>'
# 改动后复制到的目录
dest_path = '<dest_path>'

# 可继续增加监控与目标目录
# [[sync.path_list]]
# src_path = ''
# dest_path = ''
