# 备注,在ubuntu环境下使用 ibus 可能导致 kitty 无法输入中文.因为
# 本身使用 OpenGL 进行加速,使用以下命令运行使得其支持中文输入法.

# GLFW_IM_MODULE=ibus kitty

# kitty 的一些选项.
# --detach=[yes|no],是否脱离控制终端.

# 设置背景不透明
background_opacity 1
# 是否可以通过快捷键设置透明.
dynamic_background_opacity no

# 与窗口边界的距离
window_margin_width 10

# 设置字体
font_family      JetBrainsMono Nerd Font
font_size 11.0
bold_font        auto
italic_font      auto
bold_italic_font auto
# 是否禁用连字符,never表示启用,可选always.
disable_ligatures never

# 启用该选项会使得新建的窗口与之前的相同,否
# 则新建的窗口以初始化指定的宽高创建.
remember_window_size yes
# 设置初始化窗口大小,c 表示字符宽度.
initial_window_width  120c
initial_window_height 35c

# 设置光标的颜色
# cursor #cccccc

# 设置光标样式,可选为 block,beam
cursor_shape beam

# 启用光标轨迹
cursor_trail 1
# 设置光标轨迹消失速度.
cursor_trail_decay 0.3 0.6

# 通过窗口管理器关闭窗口时不需要确认
confirm_os_window_close 0

# 是否启用音频声音
enable_audio_bell yes

# 引入主题配置.
include jetbrains_darcula.conf

# 鼠标操作,选中则进行复制
copy_on_select yes

### 以下记录kitty 默认的快捷键,以下注释的为 kitty 默认快捷键.
# 快捷键机制,通过以下命令来设置
# map <key> <action>
# key 表示按按键组合, action 则是行为函数,由 kitty 定义.
# 按键组合有以下定义.
# 1. 同时按下组合,使用 + 连接,如 ctrl+shift+n
# 2. 顺序按下组合,使用 > 连接,如 ctrl+f > c,
#    表示先按下 ctrl+f,松开后再按 c.

# 默认快捷键的别名,默认就为 ctrl+shift.
# kitty_mod ctrl+shift


# 标签页快捷键管理,标签页是窗口的子集.

# 新建标签页.
# map ctrl+shift+t new_tab

# 切换到下一个标签页.
# map ctrl+shift+right next_tab
# map ctrl+tab next_tab

# 切换到下一个标签页.
# map ctrl+shift+left previous_tab
# map ctrl+shift+tab previous_tab

# 关闭当前标签页.
# map ctrl+shift+q close_tab

# 重命名当前标签页.
# map ctrl+shift+alt+t set_tab_title

# 将当前活动标签页向前移动
# map ctrl+shift+. move_tab_forward

# 将当前活动标签页向后移动
# map ctrl+shift+, move_tab_backward

# 窗口快捷键管理.

# 新建一个 kitty 窗口,等同于在终端中执行 kitty 命令.
# map ctrl+shift+n new_os_window
# map ctrl+shift+w close_window

# 复制
# map ctrl+shift+c copy_to_clipboard
# 其它可以用于复制的行为参数.
# copy_or_interrupt 复制当前选中内容,如果没有选中内容则发送中断信号.
# copy_or_noop 复制当前选中内容,如果没有选中内容则不进行任何操作.

# 粘贴
# map ctrl+shift+v paste_from_clipboard


# 其它快捷键.

# 增加字体的大小
# map ctrl+shift+equal increase_font_size

# 减小字体大小
# map ctrl+shift+minus decrease_font_size

# 切换全屏模式
# map ctrl+shift+f11 toggle_fullscreen

# 切换窗口最大化.
# map ctrl+shift+f10 toggle_maximized

# 重置终端
# map ctrl+shift+delete clear_terminal reset active

# 重新加载配置文件
# map ctrl+shift+f5 load_config_file

# 调试配置文件
# map ctrl+shift+f6 debug_config

# 直接编辑配置文件
# map ctrl+shift+f2 edit_config_file

# 打开 kitty 的 shell
# map ctrl+shift+escape kitty_shell window


# kitty 本身是终端模拟器,负责显示文本,输入,窗口管理.
# 但是它还内置了一些额外的功能,比如图片显示等.
# 使用方式为
# kitty +kitten <kitten-name> [args...]

# 例如显示在终端显示图片.
# kitty +kitten icat path/to/imagefile

# 文件区分.
# kitty +kitten diff file1 file2

# 预览官方的主题并且进行切换.
# kitty +kitten themes

# Hints,高亮显示终端的可选择的链接,命令,文件路径提示.
# kitty +kitten hints
# ctrl+shift+p>f 选择路径或者文件名并且输入到终端.

# ssh 客户端会话程序,在 kitty 终端使用默认的ssh会导致字符
# 显示异常,使用以下命令运行kitty的ssh客户端可以避免显示异常.
# kitty +kitten ssh <machine>