# Copyright (c) 2023-2024 mylinuxforwork
# Source: https://github.com/mylinuxforwork/dotfiles
# License: GNU GPL v3.0

# Modified by: carllongj carllongj@gmail.com
# Date: 2026-02-23
# Description: 本文件在原作者逻辑基础上进行了以下调整：
#   1. [修改点一：增加了输入法的自启动]
#   2. [修改点二：添加了部分注释]

#    ___       __           __           __
#   / _ |__ __/ /____  ___ / /____ _____/ /_
#  / __ / // / __/ _ \(_-</ __/ _ `/ __/ __/
# /_/ |_\_,_/\__/\___/___/\__/\_,_/_/  \__/
#

# 启动 ml4w 中的监听器,包含默认自启的脚本,如 waybar.
# Start Listeners
exec-once=~/.config/ml4w/listeners.sh --startall

# Start Polkit
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Load Wallpaper
exec-once = ~/.config/hypr/scripts/wallpaper-restore.sh

# Load Notification Daemon
exec-once = swaync

# Load GTK settings
exec-once = ~/.config/hypr/scripts/gtk.sh

# Using hypridle to start hyprlock
exec-once = hypridle

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Autostart ML4W App
exec-once = ~/.config/ml4w/scripts/ml4w-autostart

# Start autostart cleanup
exec-once = ~/.config/hypr/scripts/cleanup.sh

# Load configuration from ML4W Hyprland Settings App
exec = ~/.config/com.ml4w.hyprlandsettings/hyprctl.sh

# Loading input when start
exec-once = fcitx5 -d
